services:
  mongo:
    image: mongo:latest
    container_name: "llm_engineering_mongo"
    logging:
      options:
        max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: "llm_engineering"
      MONGO_INITDB_ROOT_PASSWORD: "llm_engineering"
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - local

  qdrant:
    image: qdrant/qdrant:latest
    container_name: "llm_engineering_qdrant"
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - local

  zenml:
    image: zenmldocker/zenml-server
    container_name: "llm_engineering_zenml"
    ports:
    - name: HTTP
      published: 8080
      target: 8080
    environment:
      ZENML_STORE_URL: mysql://zenml:bezenmydude@zenmldb/zenml
      ZENML_SERVER_AUTO_ACTIVATE: 1
      ZENML_DEFAULT_USER_NAME: admin
      ZENML_DEFAULT_USER_PASSWORD: zenml
    networks:
    - local
    depends_on:
      zenmldb:
        condition: service_healthy
  
  zenmldb:
    image: mysql
    container_name: "llm_engineering_zenmldb"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_USER: zenml
      MYSQL_PASSWORD: bezenmydude
      MYSQL_DATABASE: zenml
    volumes:
    - type: volume
      source: zenmldb_data
      target: /var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
    - local

volumes:
  mongo_data:
  qdrant_data:
  zenmldb_data:

networks:
  local:
    driver: bridge