settings:
  docker:
    parent_image: localhost:5000/zenml-base:latest
    dockerignore: .dockerignore
    environment:
      ZENML_STORE_URL: mysql://zenml:bezenmydude@zenmldb/zenml
  orchestrator.sagemaker:
    synchronous: false
    
parameters:
  user_full_name: Bryan Berry # [First Name(s)] [Last Name]
  links:
    # Personal Blog
    - https://medium.com/djangogirlsseoul-codecamp/first-time-django-c55202d1b2ec
    - https://medium.com/@bryanbeegeberry/why-i-hate-the-internet-in-korea-826d4e44d4a8
    - https://medium.com/codeseoul/automating-infrastructure-with-docker-32f85cab37c4
    - https://medium.com/@bryanbeegeberry/project-mlops-in-a-box-2025-09-28-c90800401a51
